import { NextRequest, NextResponse } from 'next/server';
import { exec } from 'child_process';
import { promisify } from 'util';
import os from 'os';
import path from 'path';
import fs from 'fs';

const execPromise = promisify(exec);

export async function GET(req: NextRequest) {
  let jsonFilePath = '';
  let pptxFilePath = '';

  try {
    // 1. Authorize Cron (support both Bearer header and query param for easy browser downloads)
    const authHeader = req.headers.get('authorization');
    const { searchParams } = new URL(req.url);
    const querySecret = searchParams.get('secret');
    const dateParam = searchParams.get('date') || new Date().toISOString().split('T')[0];
    const cronSecret = process.env.CRON_SECRET;

    const isAuthorized = !cronSecret || 
      (authHeader === `Bearer ${cronSecret}`) || 
      (querySecret === cronSecret);

    if (!isAuthorized) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // 2. Fetch report data from our reports API
    const host = req.headers.get('host') || 'localhost:3000';
    const protocol = req.url.startsWith('https') ? 'https' : 'http';
    const reportsUrl = `${protocol}://${host}/api/reports?date=${dateParam}`;

    const reportsRes = await fetch(reportsUrl);
    if (!reportsRes.ok) {
      const errMsg = await reportsRes.text();
      return NextResponse.json({ error: `Failed to fetch reports: ${errMsg}` }, { status: 500 });
    }

    const reportData = await reportsRes.json();
    if (!reportData.reports || reportData.reports.length === 0) {
      return NextResponse.json({ message: 'No reports found for this date', date: reportData.date });
    }

    // 3. Write data to a temporary JSON file for the Python script to consume
    const tempDir = os.tmpdir();
    const uniqueId = `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
    jsonFilePath = path.join(tempDir, `report-data-${uniqueId}.json`);
    pptxFilePath = path.join(tempDir, `report-${uniqueId}.pptx`);

    fs.writeFileSync(jsonFilePath, JSON.stringify(reportData, null, 2), 'utf-8');

    // 4. Run the Python generator script (supporting multiple Python binary names)
    let command = `python scripts/generate_report.py "${jsonFilePath}" "${pptxFilePath}"`;
    let runSuccess = false;
    let runError: any = null;

    try {
      await execPromise(command);
      runSuccess = true;
    } catch (err: any) {
      runError = err;
    }

    if (!runSuccess) {
      try {
        command = `python3 scripts/generate_report.py "${jsonFilePath}" "${pptxFilePath}"`;
        await execPromise(command);
        runSuccess = true;
      } catch (err: any) {
        runError = err;
      }
    }

    if (!runSuccess) {
      try {
        command = `py scripts/generate_report.py "${jsonFilePath}" "${pptxFilePath}"`;
        await execPromise(command);
        runSuccess = true;
      } catch (err: any) {
        runError = err;
      }
    }

    if (!runSuccess) {
      throw new Error(`Python execution failed: ${runError?.message || 'Unknown error'}`);
    }

    // 5. Read the generated PPTX file
    if (!fs.existsSync(pptxFilePath)) {
      throw new Error('PPTX file was not generated by the python script.');
    }

    const buffer = fs.readFileSync(pptxFilePath);

    // 6. Optional: Upload to Discord if Webhook is set
    const discordUrl = process.env.DISCORD_WEBHOOK_URL;
    if (discordUrl) {
      try {
        const formData = new FormData();
        const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation' });
        formData.append('file', blob, `report-${dateParam}.pptx`);
        formData.append('payload_json', JSON.stringify({
          content: `📊 **BDReport PowerPoint Generated from Template**\nDate: ${reportData.date}`
        }));
        await fetch(discordUrl, {
          method: 'POST',
          body: formData,
        });
      } catch (err) {
        console.error('Failed to post to Discord webhook:', err);
      }
    }

    // 7. Return file download response
    const response = new Response(buffer, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="report-${dateParam}.pptx"`,
      },
    });

    return response;
  } catch (error: any) {
    console.error('PPTX generation error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  } finally {
    // Cleanup temporary files
    try {
      if (jsonFilePath && fs.existsSync(jsonFilePath)) {
        fs.unlinkSync(jsonFilePath);
      }
      if (pptxFilePath && fs.existsSync(pptxFilePath)) {
        fs.unlinkSync(pptxFilePath);
      }
    } catch (cleanupErr) {
      console.error('Failed to cleanup temporary files:', cleanupErr);
    }
  }
}
